name: Publish Docker Image & Deploy to Remote Server

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Dockerfile*'
  release:
    # 表示在创建新的 Release 时触发
    types: [created]

jobs:
  build_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date time
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/buptreasure-client:${{ steps.date.outputs.today }}
            ${{ secrets.DOCKER_USERNAME }}/buptreasure-client:latest
  deploy:
    name: Deploy to Remote Server
    needs: build_docker
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SUDO_PASSWORD }}
          key: ${{ secrets.PR_KEY }}
          script: |
            cd /home/lantu/buptreasure
            docker-compose up -d --force-recreate buptreasure-client