name: Deploy to Remote Server

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Dockerfile*'
  release:
    # 表示在创建新的 Release 时触发
    types: [created]

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Build on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/nginx/html/buptreasure
          rm -rf dist
          git clone https://github.com/A-CS99/BUPTreasureClient.git
          cd BUPTreasureClient
          npm install
          npm run build
          mv dist /home/nginx/html/buptreasure/
          cd /home/nginx/html/buptreasure
          rm -rf BUPTreasureClient